site_name: Homelab Docs
site_url: https://docs.chrisyocum.com
site_dir: public
site_description: Stop using your head to store documentation. Write it here!
repo_name: homelab-docs
repo_url: https://github.com/tronyx/homelab-docs

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      toc_depth: 4
plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true # Optional: to also show creation date
      type: datetime # or datetime, iso_date, iso_datetime, timeago
      timezone: America/New_York
      locale: en
  - git-authors
  - mkdocs-video
  - open-in-new-tab:
      add_icon: true
#  - optimize:
#      enabled: !ENV [CI, false]
#      cache: true
#      optimize_png: true
#      optimize_jpg: true
  - search
extra_css:
  - overrides/assets/stylesheets/extra.css
theme:
  name: material
  logo: overrides/assets/images/icons/icon.png
  favicon: overrides/assets/images/icons/favicon.png
  custom_dir: docs/overrides
  font:
    text: DM Sans
    code: Fira Code
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.lazy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navivation.top
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/gitlab
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ironmountain
      name: Iron Mountain on Facebook
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/iron-mountain
      name: Iron Mountain on LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/ironmountain
      name: Iron Mountain on YouTube
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ironmountain
      name: Iron Mountain on X
copyright: Copyright &copy; 2026 Iron Mountain

nav:
  - HOME:
    - index.md
    - ITAR: itar.md
    - DMS: dms.md
    - NA DMS ITAR EIT:
      - The Team: team/org-chart.md
      - Training Schedule:
        - Getting Started: team/training/get-started.md
        - Day One: team/training/day-one.md
        - Week 1: team/training/week-1.md
        - Week 2: team/training/week-2.md
        - Week 3: team/training/week-3.md
      - Shift Turnover: team/turnover.md
      - FAQ: team/faq.md
      - Quick Links: team/quick-links.md
      - Project Sites:
        - team/project-sites/index.md
        - Atlanta, GA: team/project-sites/atga.md
        - Boyers, PA: team/project-sites/bopa.md
        - Dallas, TX: team/project-sites/datx.md
        - Frankfort, KY: team/project-sites/frky.md
        - Fredericksburg, VA: team/project-sites/frva.md
        - Jessup, MD: team/project-sites/jemd.md
        - Kent, WA: team/project-sites/kewa.md
        - Lee's Summit, MO: team/project-sites/lsmo.md
        - Mesa, AZ: team/project-sites/mesa.md
        - Royersford, PA: team/project-sites/ropa.md
        - St Louis, MO: team/project-sites/slmo.md
        - Tampa, FL: team/project-sites/tafl.md
        - West Columbia, SC: team/project-sites/scdor.md
  - TOOLS:
    - tools/index.md
    - HARDWARE:
      - IBML:
        - tools/hardware/ibml/index.md
        - Setup: tools/hardware/ibml/setup.md
        - CaptureSuite: tools/hardware/ibml/capturesuite.md
        - Troubleshooting: tools/hardware/ibml/troubleshooting.md
      - Kodak: tools/hardware/kodak.md
      - OPEX:
        - tools/hardware/opex/index.md
        - Installation: tools/hardware/opex/installation.md
        - Upgrade: tools/hardware/opex/upgrades.md
        - Monitoring: tools/hardware/opex/monitoring.md
        - Event Logger: tools/hardware/opex/event-logger.md
        - OAK Updates: tools/hardware/opex/oak-updates.md
      - nextScan: tools/hardware/nextscan.md
    - SOFTWARE:
      - Kofax:
        - tools/software/kofax/index.md
        - Installations:
          - FISMA: tools/software/kofax/installations/fisma.md
          - GovCentral: tools/software/kofax/installations/govcentral.md
          - IM Modules: tools/software/kofax/installations/modules.md
          - Misc: tools/software/kofax/installations/misc.md
        - Monitoring: tools/software/kofax/monitoring.md
        - Tools: tools/software/kofax/tools.md
        - Troubleshooting: tools/software/kofax/troubleshooting.md
      - Insight DXP:
        - tools/software/insight/index.md
        - HITL: tools/software/insight/hitl.md
      - IDP: tools/software/idp.md
      - OCR: tools/software/ocr.md
      - Globalscape:
        - tools/software/globalscape/index.md
        - Configuration: tools/software/globalscape/config.md
      - SQL: tools/software/sql.md
      - CTERA: tools/software/ctera.md
      - FADGI: tools/software/fadgi.md
  - RESPONSIBILITIES:
    - Daily: responsibilities/daily.md
    - Deployments:
      - responsibilities/deployments/index.md
      - Batch Classes: responsibilities/deployments/batch-classes.md
      - IDP:
        - Linux: responsibilities/deployments/idp-linux.md
        - Windows: responsibilities/deployments/idp-windows.md
      - Globalscape: responsibilities/deployments/globalscape.md
    - Computers:
      - responsibilities/computers/index.md
      - GovCentral:
        - Setup:
          - Re-Image: responsibilities/computers/govcent/setup/reimage.md
          - Workstations: responsibilities/computers/govcent/setup/workstations.md
          - Laptops: responsibilities/computers/govcent/setup/laptops.md
        - Troubleshooting:
          - Remote Connections: responsibilities/computers/govcent/troubleshooting/remcons.md
      - Corp/FISMA: responsibilities/computers/corp-fisma/index.md
    - User Management:
      - Active Directory:
        - responsibilities/user-management/active-directory/index.md
        - Corp/FISMA: responsibilities/user-management/active-directory/corp-fisma.md
        - GovCentral: responsibilities/user-management/active-directory/govcentral.md
      - IMGS Okta: responsibilities/user-management/imgs-okta.md
      - Cisco Duo: responsibilities/user-management/duo.md
      - HITL/Insight: responsibilities/user-management/hitl.md
    - YubiKeys: 
      - responsibilities/yubikeys/index.md
      - Configuration:
        - responsibilities/yubikeys/configuration/index.md
        - YubiKey Manager CLI: responsibilities/yubikeys/configuration/ykman.md
        - YubiKey Personalization Tool: responsibilities/yubikeys/configuration/yubikey-personalization-tool.md
        - YubiKey Authenticator: responsibilities/yubikeys/configuration/yubico-authenticator.md
        - YubiKey Manager GUI: responsibilities/yubikeys/configuration/yubikey-manager-gui.md
      - Management:
        - OKTA: responsibilities/yubikeys/management/okta.md
        - Cisco Duo: responsibilities/yubikeys/management/duo.md
    - Monitoring:
      - responsibilities/monitoring/index.md
      - Utilities:
        - DataDog: responsibilities/monitoring/datadog.md
        - SolarWinds: responsibilities/monitoring/solarwinds.md
    - On-Call:
      - responsibilities/on-call/index.md
      - Schedule: responsibilities/on-call/schedule.md
      - Weekly Checks: responsibilities/on-call/weekly-checks.md
    - SCAP Scans: responsibilities/scap-scans.md
    - Tickets & Requests: responsibilities/tickets.md
    - Miscellaneous: responsibilities/misc.md
  - REPORTING:
    - IMCore: reporting/imcore.md
    - WebStatus: reporting/webstatus.md
    - IMReports: reporting/imreports.md
    - Scan Volume: reporting/scan-volume.md
  - INFRASTRUCTURE:
    - infra/index.md
    - Hardware:
      - Inventory Sheets: infra/hardware/inventory.md
      - Rack Layouts: infra/hardware/rack-layouts.md