site_name: Homelab Docs
site_url: https://docs.chrisyocum.com
site_dir: public
site_description: Stop using your head to store documentation. Write it here!
repo_name: homelab-docs
repo_url: https://github.com/tronyx/homelab-docs

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      toc_depth: 4
plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true # Optional: to also show creation date
      type: datetime # or datetime, iso_date, iso_datetime, timeago
      timezone: America/New_York
      locale: en
  - git-authors
  - mkdocs-video
  - open-in-new-tab:
      add_icon: true
#  - optimize:
#      enabled: !ENV [CI, false]
#      cache: true
#      optimize_png: true
#      optimize_jpg: true
  - search
extra_css:
  - overrides/assets/stylesheets/extra.css
theme:
  name: material
  logo: overrides/assets/images/icons/icon.png
  favicon: overrides/assets/images/icons/favicon.png
  custom_dir: docs/overrides
  font:
    text: DM Sans
    code: Fira Code
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.lazy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navivation.top
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/gitlab
copyright: Copyright &copy; 2026 Chris Yocum

nav:
  - HOME:
    - index.md
  - PRIMARY LAB:
    - labs/primary.md
  - GITOPS LAB:
    - labs/gitops.md
  - INFRASTRUCTURE:
    - infra/index.md